### ISSUE TITLE
Image groups

### ISSUE THREAD

**Issue by johnhearfield** [roXon/Darkbox-Gallery#1]
Hi,

Would it be possible to group the images into a gallery group, and so when you are viewing the gallery, the previous/next button shows the previous/next image in that group instead of being global?

I know a few gallery plugins do something similar, but the styling of yours is much cleaner and simpler, and feels more lightweight.

**Comment by rokobuljan** [comment]
Hi @johnhearfield 
Thanks for the heads-up. And thanks for the great tip (wanted to add that feature for a long time but never had the time to)

**New features:**

 1. Groups using `data-darkbox-group="someName"`  
 1. CSS3 animated loading spinner   
 1. PREV/NEXT now hide if darkbok shows a single image.  
 1. Stats counter (if darkbox opens as group a counter current/total will show-up)

**Major change**
In the earlier version all `data-darkbox` elements were linked together -   
In the new version the gallery will show only that image. Groups should be used from now on.
