### ISSUE TITLE
Only works with your provided images

### ISSUE THREAD

**Issue by wftico** [roXon/Darkbox-Gallery#2]
Hey,

when I try to use my own images (doesn't matter if I upload them only or use them from a directory, the gallery wont work. I see the image, but when I click it I get the loading sequence forever. The zoomed picture never shows.

Do you have any idea why this is?

How do you work with the script files btw... Is it enough to add it on the <head> section? Or do I need to add it somewhere else, or a ready function and so on?

Thanks for any help! :)

**Comment by rokobuljan** [comment]
@wftico good call, thanks! Overall - inside the darkbox.js it's missing the DOM ready handler -  I'll review that issue shortly. In the meantime, to see it working please place your  `<script>` in a non-blocking manner - preferably right before the closing `</body>` tag. 
Thanks again for the valuable pair of eyes

**Comment by rokobuljan** [comment]
The missing DOM ready is now added within the IIFE.
Provided also a darkbox.min.js
